"""Install systemd --user unit for roxabi-sense (ADR-002 / goal 2.7a)."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

from roxabi_sense.paths import xdg_config_home

_UNIT_NAME = "roxabi-sense.service"

_UNIT_TEMPLATE = """\
# Generated by `sense install-service`
# graphical-session: WAYLAND_DISPLAY / AT-SPI available after login

[Unit]
Description=roxabi-sense workstation attention journal
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart={exec_start}
Restart=always
RestartSec=5

[Install]
WantedBy=graphical-session.target
"""


def resolve_sense_binary() -> Path:
    which = shutil.which("sense")
    if which:
        return Path(which).resolve()
    home_bin = Path.home() / ".local" / "bin" / "sense"
    if home_bin.is_file():
        return home_bin.resolve()
    # Fallback: current interpreter -m
    return Path(sys.executable)


def unit_path() -> Path:
    return xdg_config_home() / "systemd" / "user" / _UNIT_NAME


def write_unit(*, exec_start: str | None = None, dest: Path | None = None) -> Path:
    path = dest or unit_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    binary = exec_start or str(resolve_sense_binary())
    # If binary is python, run module
    if binary.endswith(("python", "python3")) or "python" in Path(binary).name:
        cmd = f"{binary} -m roxabi_sense.cli daemon"
    else:
        cmd = f"{binary} daemon"
    body = _UNIT_TEMPLATE.format(exec_start=cmd)
    path.write_text(body, encoding="utf-8")
    return path


def install_service(*, reload: bool = True) -> tuple[int, str]:
    """
    Write user unit and daemon-reload.

    Returns (exit_code, message).
    """
    binary = resolve_sense_binary()
    path = write_unit(exec_start=str(binary))
    lines = [f"wrote {path}", f"ExecStart={binary} daemon"]
    if "WantedBy=graphical-session.target" not in path.read_text(encoding="utf-8"):
        return 1, "unit missing WantedBy=graphical-session.target"
    if reload:
        try:
            subprocess.run(
                ["systemctl", "--user", "daemon-reload"],
                check=False,
                capture_output=True,
                timeout=10,
            )
            lines.append("systemctl --user daemon-reload: ok")
            lines.append("enable: systemctl --user enable --now roxabi-sense.service")
            lines.append(
                "hint: systemctl --user import-environment "
                "WAYLAND_DISPLAY XDG_RUNTIME_DIR XDG_SESSION_TYPE"
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            lines.append(f"daemon-reload skipped: {exc}")
    return 0, "\n".join(lines)
