#!/usr/bin/env bash
# Generated by dev-core worktreeScaffold — do not edit by hand.
# Concerns: uv-venv-symlink, lefthook-hookspath-fix
# Re-generate with: /stack-setup --force (or /env-setup retrofit)
set -euo pipefail

# ─── uv-venv-symlink ──────────────────────────────────────────
# remove symlink only — never touch a real directory
[ -L .venv ] && rm .venv || true

# ─── lefthook-hookspath-fix ──────────────────────────────────────────
:
