#!/usr/bin/env bash
# Generated by dev-core worktreeScaffold — do not edit by hand.
# Concerns: uv-venv-symlink, lefthook-hookspath-fix
# Re-generate with: /stack-setup --force (or /env-setup retrofit)
set -euo pipefail

# ─── uv-venv-symlink ──────────────────────────────────────────
MAIN_REPO=$(git worktree list --porcelain | awk '/^worktree / {print $2; exit}')

if [ -z "${MAIN_REPO:-}" ] || [ ! -d "${MAIN_REPO}/.venv" ]; then
  echo "worktree-setup: main repo .venv not found at ${MAIN_REPO:-?} — skipping" >&2
  exit 0
fi

if [ "${PWD}" = "${MAIN_REPO}" ]; then
  echo "worktree-setup: running inside main repo, refusing to symlink .venv onto itself" >&2
  exit 0
fi

if [ -L .venv ]; then
  rm .venv
elif [ -d .venv ]; then
  echo "worktree-setup: .venv already exists as a real directory — leaving it untouched" >&2
  exit 0
fi

ln -s "${MAIN_REPO}/.venv" .venv
echo "worktree-setup: linked .venv → ${MAIN_REPO}/.venv"

# ─── lefthook-hookspath-fix ──────────────────────────────────────────
# in worktrees, lefthook installs core.hooksPath relative to the worktree git dir (wrong —
# git uses the common dir for hooks). unset so git falls back to the default hooks path.
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
GIT_COMMON_DIR=$(git rev-parse --git-common-dir 2>/dev/null)
if [ "${GIT_DIR}" != "${GIT_COMMON_DIR}" ]; then
  git config --unset-all core.hooksPath 2>/dev/null || true
fi
